version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      day: "monday"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      day: "monday"
      timezone: Europe/Paris
    open-pull-requests-limit: 10